//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMeTieneJarto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class Empleados
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        [ScaffoldColumn(true)]
        [StringLength(11, ErrorMessage = "La cedula debe tener 11 caracteres")]
        public string Cedula { get; set; }
        public decimal Salario { get; set; }
        public System.DateTime Fecha_ingreso { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public int Cargo_ID { get; set; }
        public string Departamento_ID { get; set; }
    
        public virtual Cargos Cargos { get; set; }
        public virtual Departamentos Departamentos { get; set; }
    }
}
